### ISSUE TITLE
Hastads failing on multi attack

### ISSUE THREAD

**Issue by Scalpel78** [Ganapati/RsaCtfTool#101]
I have three .pub files, and I'm trying to do a multi-attack using the latest version from GitHub, but it fails in hastads.py.

```
python3 ./RsaCtfTool.py --publickey "*.pub" --private
[*] Multikey mode using keys: 1.pub, 3.pub, 2.pub
[*] Performing hastads attack.
Traceback (most recent call last):
  File "./RsaCtfTool.py", line 250, in <module>
    found = attackobj.attack_multiple_keys(args.publickey, attacks_list)
  File "/blabla/RsaCtfTool/lib/rsa_attack.py", line 151, in attack_multiple_keys
    self, self.publickey, self.cipher
  File "/blabla/RsaCtfTool/attacks/multi_keys/hastads.py", line 59, in attack
    for _ in cipher:
TypeError: 'NoneType' object is not iterable
```

If I manually specify one of the other attack modes, it completes the run. But if I specify 'hastads' it fails with same error.

**Comment by Ganapati** [comment]
Hi,
Can you give me the .pub files ?
I'll try and patch the code if needed.

**Comment by Scalpel78** [comment]
Hi, here they are.

```
-----BEGIN PUBLIC KEY-----
MIIBIDANBgkqhkiG9w0BAQEFAAOCAQ0AMIIBCAKCAQEArcqhaXwxAL8Mr+M4Dmqy
usq4RvREYy/f4Yp8v/3WGLCa+vVFJWQ5gijPqfg5yedkPnHXYaFNS60vTQeDXtUG
KEMVlUxy38kMI9n0ENq7kVdwg/LuoeuK0oWgpSAFyR8Wl9I30DCmtnk+3TfqeR+i
ySbPCw3QD5Sta/iNSRM5nyX8CKC104gtTako+0t+ynW2TDtnhNhecAUQxtt/+d3g
otMnaLKAA45j64r4p7JItGG7A+NQtJ9GAvcD7WqygYoyCG5cAyzWfaPydDgB3uVV
Gwkiw3JniAxe7Kyt9g9tGXlfFYP7WwR8zc/bMEn78+B3TgEZU2FwhN6fGdYc6atb
OQIBAw==
-----END PUBLIC KEY-----

-----BEGIN PUBLIC KEY-----
MIIBIDANBgkqhkiG9w0BAQEFAAOCAQ0AMIIBCAKCAQEA0Iku6gE7OeajoWeKtsIg
d0mm00fJnJjr69Fd+gY6yrL3QkzFGBLrZzS7w4+dDBCzWVSbfIg+fT8J954sZlL+
sFaCt/deJ9VwqniRDlk2aiYEyJrk1GDdKF3T6+IwmTvClMoLgaF/KbT1hOyPZunh
suqBnjmQo4T3WmQ91+f+eDY1bUq1+xCfj0+yPpDRgw0OL5DgOGJJS01SccwV5GPs
DMZOm77RaMXEHTktcxbsQSo+wt2IaOr+9qe480fcAN5CSRKr+JbaNPA6WvA9jjuT
R+YeVTm3W8y/VfHA7FAg7ioc6+87KqN9rxTIJS0gdnRvCpDp8XoAGF476Dw9Jmrj
GQIBAw==
-----END PUBLIC KEY-----

-----BEGIN PUBLIC KEY-----
MIIBIDANBgkqhkiG9w0BAQEFAAOCAQ0AMIIBCAKCAQEAtk2A3EQx8ujUaCk30blI
DYwz3p+2E24VWoZzwwWGU3IETXvXNXK5D0quLxCTXiUPEK5flAh1v6EW1P8o7I0o
b4xeXGXsGwnjopPQ+BxznsGYB1I3VDqN7o1O8g9psdMXUps9FEiDoqkmqmbhODC4
6hvGAw3eki08PfrFFNiQ8rdueBJO6dPf8jrghgYfnKNaFi4YadFxuzi49PB72g/9
NmEQ/Ls+L4jDmwP8iqQnE3Cs4yzN7lmPd25mzU7BfSFtpf/TqjM8BHW3s5aE78aW
40Iel/URrYBW9X/VtXjmC7wQMo7MOnrtawmOH0WAsUflOAeEIN4/yoffAI7n3xVI
TQIBAw==
-----END PUBLIC KEY-----

```

**Comment by Scalpel78** [comment]
If you can, just make a note here when you have copied them, and I'll remove them. They are from an ongoing CTF that lasts a couple of more hours so I'd like to take them down when you have made copies.

**Comment by Ganapati** [comment]
message removed, i'll check, to you have a cipher to decrypt?

**Comment by Scalpel78** [comment]
Great, here are the ciphers.
```
c1=515274042976912179894435774656907420040599503456517078488056218986662017260212389975972477279505310799399071383390618892499008790928347543017765027618590150794317674792875250152206518326158674718404382617692169589911938548819188733852354294583496715425255584973283840789780326402769751705164900106921523637157271605500111846563844641773661723255718653040958019618435501230171699432186518803652675691180548548982155426472648502704469425298466513665043628724497448475714424482446137414939511691724839553567514050622159418495196773388690852258256550787962177196383253952227153557220272199293397879908308572668952866439

c2=10512934566887371506285681495672139256544177416158977932082410009242386741198073874632763611137937701329570263046854521709347241390006612379393018933295475369159148328248445221357906382527678877429535168220389698475391828837227453358681276167720605617228338487308750653165147019400915842904872988789759529121710032871148507314874152494680057046977274373381326003405301191489108322498519602528688873942243307708631394538177629868515911161222795303220989599519719169300455717641863368473309673489958952173445661451265442004625237606054046962062434813126456494957846077185121041599277143211160596207640833275850170891378

c3=4122591425712279559823043898131225014447235394996958162806737555257607173149332839353292933732548212376056402900761362427837044396517072345683265668973735260384169928448531246071624967168190024583028639591981238222340513125989229227761894026521238496145716707176637113415430809586007230597253976748507442809040629281971868442704017013258355403718545489677897799000961350863824810217217745918503635905775610161826572608564207497464646323778407843991683950506484189720225535503643332574132841288909783555334280205740975729691459011043954137669831817945210956835398278009161994675851980163314376477384045294293755909874
```
and `e = 3`

**Comment by Ganapati** [comment]
yours keys and cipher don't return anything looking like a flag, are you sure of the keys, the ciphers and if key1:c1, key2:c2 key3:c3 ?

**Comment by Scalpel78** [comment]
Hmm, that is strange.

Here is the initial problem, copied directly from the challenge text
```
c1=515274042976912179894435774656907420040599503456517078488056218986662017260212389975972477279505310799399071383390618892499008790928347543017765027618590150794317674792875250152206518326158674718404382617692169589911938548819188733852354294583496715425255584973283840789780326402769751705164900106921523637157271605500111846563844641773661723255718653040958019618435501230171699432186518803652675691180548548982155426472648502704469425298466513665043628724497448475714424482446137414939511691724839553567514050622159418495196773388690852258256550787962177196383253952227153557220272199293397879908308572668952866439

c2=10512934566887371506285681495672139256544177416158977932082410009242386741198073874632763611137937701329570263046854521709347241390006612379393018933295475369159148328248445221357906382527678877429535168220389698475391828837227453358681276167720605617228338487308750653165147019400915842904872988789759529121710032871148507314874152494680057046977274373381326003405301191489108322498519602528688873942243307708631394538177629868515911161222795303220989599519719169300455717641863368473309673489958952173445661451265442004625237606054046962062434813126456494957846077185121041599277143211160596207640833275850170891378

c3=4122591425712279559823043898131225014447235394996958162806737555257607173149332839353292933732548212376056402900761362427837044396517072345683265668973735260384169928448531246071624967168190024583028639591981238222340513125989229227761894026521238496145716707176637113415430809586007230597253976748507442809040629281971868442704017013258355403718545489677897799000961350863824810217217745918503635905775610161826572608564207497464646323778407843991683950506484189720225535503643332574132841288909783555334280205740975729691459011043954137669831817945210956835398278009161994675851980163314376477384045294293755909874

n1=21939147590581954242131893557689750173730181114330873782062274456630281986233643990882568426690149971468987847436717513764939861105600249325682418749886588739440853385485272501856860578476795830603738468829294920737586209822299603185425324611481798231193950636987017718955070420091525231666894903436050998112803225822333684113551754209802262129292376015861410644289380376439390552627189657966103965089679163295591136464541998227543058082734503570960156783196006833967361311083486266118899788620317372054292861892020849652213277431575285275801196626852675579752895079650118836892859390462805733596279690076656763624249

n2=26325215018784165663958487526715385161171636566916698114816183716597566424675870012796860473421390775180027083457908584461525282815469520282303059318923930531826588673345113634118988713179894971211405380241575065877886390347877768297280022387015195069836149198306647472534681286406136303674462323742151285361538383784282113898065157278366533587767199303585208673225974716800760227497569577072903884939422787710986913747191378087554442395968729847569180921093186599977266346501947184849099856506537976370069200813758143237937721729073822639191799709052936074831322440705620902220824412476988222346922869104007199777561

n3=23013589835547680503802140462487647716102548445081685245087901486321520435018899614072711065158868927754813316329675676910885474767916372370942795565358071859270832973837949423193707764788999822539648518439967218163608118921979697363190728350735745938069012584523314223346479156208977445194408267152808800890485882602068876756801123087623323707553203656108124651989136578687688847505350883163751096338640206246619001851586459510648241545637475283654557530338836698680934504086346810521919864048046078444168117563048636886066060497385368685340990757248020960409380316695810483273153565980791846594355984630591111120973

e=3
```

**Comment by Ganapati** [comment]
I tried 2 tools, and same result...

b" \xea\xbf3\x19\xbf\xad\xeb,\xbd3\x7fUg\xc1*\x92\xe2\xc9\xcd\xc36\x19\xdd\xe9\x1b\xad\xfdu\x8e\x7f\xed\xff\xcb\x11wL\x90\xcb\x90&\xac\x96r\x82\xb4[\x11\xf1@9v,\xb0*\xa3\xaf\xa9\xac\xd1o\xef\x98`\x07\x8e\x1an\xb1*\xfc\x1e\xd3A\xae[\xf3\x14h\x14O\xf1g\x1aOd\xa5c'\x86\x90\xedp\xd3$\x9cI=\xf9\xfd-\x90\xee\x96!;\xc2\xab\x1b\xb6^\x84\x08\x1a\xf3\x10L\x0e>g\x0f lj\x0f\xe5\xbcnHEJ\xa9\x0f\x83"

**Comment by Scalpel78** [comment]
Strange. I see the challenge has been solved by 100+ teams, so something is weird somewhere... Hmm.

**Comment by Ganapati** [comment]
Can you send me the ctf and a write up if you find  one?

**Comment by Scalpel78** [comment]
Here is the official writeup for it: https://gitlab.com/acurless/wpictf-20-illuminati-confirmed

**Comment by Ganapati** [comment]
Thx !
