### ISSUE TITLE
 gmpy2.mpz is not a type object

### ISSUE THREAD

**Issue by pmcstjean** [Ganapati/RsaCtfTool#112]
I'm trying to run an ecm2 attack and receive an error about gmpy2

[*] Testing key /tmp/tmp4rg45p9c.
[*] Performing ecm2 attack on /tmp/tmp4rg45p9c.
[*] ECM2 Method can run forever and may never succeed, timeout set to 30sec. Hit Ctrl-C to bail out.
Traceback (most recent call last):
  File "/home/kali/Documents/RsaCtfTool/attacks/single_key/../../sage/ecm2.sage.py", line 4, in <module>
    from sage.all_cmdline import *   # import sage library
  File "/usr/lib/python3/dist-packages/sage/all_cmdline.py", line 26, in <module>
    from sage.all import *
  File "/usr/lib/python3/dist-packages/sage/all.py", line 93, in <module>
    from sage.misc.all       import *         # takes a while
  File "/usr/lib/python3/dist-packages/sage/misc/all.py", line 27, in <module>
    from .html import html
  File "/usr/lib/python3/dist-packages/sage/misc/html.py", line 20, in <module>
    from sage.misc.latex import latex
  File "/usr/lib/python3/dist-packages/sage/misc/latex.py", line 570, in <module>
    from sage.structure.sage_object import SageObject
  File "/usr/lib/python3/dist-packages/sage/structure/__init__.py", line 2, in <module>
    import sage.structure.element
  File "sage/structure/parent.pxd", line 12, in init sage.structure.element (build/cythonized/sage/structure/element.c:34167)
  File "sage/structure/coerce.pxd", line 11, in init sage.structure.parent (build/cythonized/sage/structure/parent.c:27571)
  File "gmpy2.pxd", line 98, in init sage.structure.coerce (build/cythonized/sage/structure/coerce.c:23176)
TypeError: gmpy2.mpz is not a type object

Any clue ?

**Comment by Ganapati** [comment]
I've pushed a new requirements.txt today, I hope it will solve your bug.
