### ISSUE TITLE
gmpy2.mpz is not a type object

### ISSUE THREAD

**Issue by leaf7th** [Ganapati/RsaCtfTool#117]
[*] Performing smallfraction attack on /tmp/tmptnllvhrz.
Traceback (most recent call last):
  File "/home/nook/ctf/RsaCtfTool/attacks/single_key/../../sage/smallfraction.sage.py", line 4, in <module>
    from sage.all_cmdline import *   # import sage library
  File "/usr/lib/python3/dist-packages/sage/all_cmdline.py", line 26, in <module>
    from sage.all import *
  File "/usr/lib/python3/dist-packages/sage/all.py", line 93, in <module>
    from sage.misc.all       import *         # takes a while
  File "/usr/lib/python3/dist-packages/sage/misc/all.py", line 27, in <module>
    from .html import html
  File "/usr/lib/python3/dist-packages/sage/misc/html.py", line 20, in <module>
    from sage.misc.latex import latex
  File "/usr/lib/python3/dist-packages/sage/misc/latex.py", line 570, in <module>
    from sage.structure.sage_object import SageObject
  File "/usr/lib/python3/dist-packages/sage/structure/__init__.py", line 2, in <module>
    import sage.structure.element
  File "sage/structure/parent.pxd", line 12, in init sage.structure.element (build/cythonized/sage/structure/element.c:34167)
  File "sage/structure/coerce.pxd", line 11, in init sage.structure.parent (build/cythonized/sage/structure/parent.c:27571)
  File "gmpy2.pxd", line 98, in init sage.structure.coerce (build/cythonized/sage/structure/coerce.c:23176)
TypeError: gmpy2.mpz is not a type object

I’m using the latest requirements.txt

**Comment by AstralPresence** [comment]
Same issue faced.

**Comment by shinmai** [comment]
You need gmpy2 2.1.x or later, PyPI installs 2.0.8. I resolved this by uninstalling with pip and installing 2.1.0 through the distro's package manager.

**Comment by desdic** [comment]
For me on Focal it was solved by

six==1.12.0
gmpy2==2.1.0b5

**Comment by taj0023** [comment]
oh thank you @desdic

**Comment by Ganapati** [comment]
thx, i've updated the requirements.txt

**Comment by kansitan** [comment]
is there a possible tutorial in termux please 😘
