### ISSUE TITLE
ValueError: invalid literal for int() with base 10: "b''" in single_key/binary_polinomial_factoring.py

### ISSUE THREAD

**Issue by l3ouu4n9** [Ganapati/RsaCtfTool#139]
python3 RsaCtfTool.py -e 101 -n 52035749 --uncipher 31018357
private argument is not set, the private key will not be displayed, even if recovered.

[*] Testing key /tmp/tmpfgax3htr.
[*] Performing binary_polinomial_factoring attack on /tmp/tmpfgax3htr.
Traceback (most recent call last):
  File "RsaCtfTool.py", line 265, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/home/lai/leo/crypto/RsaCtfTool/lib/rsa_attack.py", line 193, in attack_single_key
    self, self.publickey, self.cipher
  File "/home/lai/leo/crypto/RsaCtfTool/attacks/single_key/binary_polinomial_factoring.py", line 30, in attack
    p = int(sageresult[0])
ValueError: invalid literal for int() with base 10: "b''"

There can be an error for type conversion when sage got no result.

**Comment by Ganapati** [comment]
Fixed in latest commit !
