### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '-e'

### ISSUE THREAD

**Issue by jshookz** [Ganapati/RsaCtfTool#170]
Had to install SageMath and just did a git clone on the master. When I run the following code from the RsaCtfTool directory it errors out every time: 

─$ python3 RsaCtfTool.py **-e** 5 **-n** 724492310922571088929727 **--uncipher** 21924480357
[*] Testing key /tmp/tmpy4oiw9k3.
Traceback (most recent call last):
  File "/home/kali/RsaCtfTool/RsaCtfTool.py", line 283, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/home/kali/RsaCtfTool/lib/rsa_attack.py", line 176, in attack_single_key
    self.load_attacks(attacks_list)
  File "/home/kali/RsaCtfTool/lib/rsa_attack.py", line 109, in load_attacks
    attack_module = importlib.import_module(
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/kali/RsaCtfTool/attacks/single_key/z3_solver.py", line 17, in <module>
    r = solve(int(sys.argv[1]))
ValueError: invalid literal for int() with base 10: '-e'

This has happened every time so far. Any help would be appreciated!

**Comment by ehhthing** [comment]
Workaround: delete https://github.com/Ganapati/RsaCtfTool/blob/master/attacks/single_key/z3_solver.py#L17-L18, seems to be debugging code that wasn't removed.

**Comment by Ganapati** [comment]
Fixed with latest PR
