### ISSUE TITLE
ValueError: invalid literal for int() with base 10: '--publickey'

### ISSUE THREAD

**Issue by bottles** [Ganapati/RsaCtfTool#172]
With the latest master version, I got this error, please help.

```
root@kali:/opt/RsaCtfTool# python3 RsaCtfTool.py --publickey "rootauthorizedsshkey.pub" --private --verbosity INFO

[*] Testing key rootauthorizedsshkey.pub.
Traceback (most recent call last):
  File "/opt/RsaCtfTool/RsaCtfTool.py", line 283, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/opt/RsaCtfTool/lib/rsa_attack.py", line 176, in attack_single_key
    self.load_attacks(attacks_list)
  File "/opt/RsaCtfTool/lib/rsa_attack.py", line 109, in load_attacks
    attack_module = importlib.import_module(
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/RsaCtfTool/attacks/single_key/z3_solver.py", line 17, in <module>
    r = solve(int(sys.argv[1]))
ValueError: invalid literal for int() with base 10: '--publickey'
```

rootauthorizedsshkey.pub

```
-----BEGIN PUBLIC KEY-----
MIIBIDANBgkqhkiG9w0BAQEFAAOCAQ0AMIIBCAKBgQYHLL65S3kVbhZ6kJnpf072
YPH4Clvxj/41tzMVp/O3PCRVkDK/CpfBCS5PQV+mAcghLpSzTnFUzs69Ys466M//
DmcIo1pJGKy8LDrwdpsSjVmvSgg39nCoOYMiAUVF0T0c47eUCmBloX/K8QjId6Pd
D/qlaFM8B87MHZlW1fqe6QKBgQVY7NdIxerjKu5eOsRE8HTDAw9BLYUyoYeAe4/w
Wt2/7A1Xgi5ckTFMG5EXhfv67GfCFE3jCpn2sd5e6zqBoKlHwAk52w4jSihdzGAx
I85LArqOGc6QoVPS7jx5h5bK/3Oqm3siimo8O1BJ+mKGy9Owg9oZhBl28CfRyFug
a99GCw==
-----END PUBLIC KEY-----

```

Python version
```
root@kali:/opt/RsaCtfTool# python3 --version
Python 3.9.1+
```

**Comment by Ganapati** [comment]
Fixed in latest commit :
