### ISSUE TITLE
z3_solver AttributeError: 'NoneType' object has no attribute 'as_string'

### ISSUE THREAD

**Issue by cookiekrieger** [Ganapati/RsaCtfTool#184]
If I run the z3_solver with a public key, or a e and n I get:
[*] Performing z3_solver attack on ./key.pub.
[!] Timeout.
Traceback (most recent call last):
  File "/home/lobsang/CTFtools/RsaCtfTool/./RsaCtfTool.py", line 292, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/home/lobsang/CTFtools/RsaCtfTool/lib/rsa_attack.py", line 209, in attack_single_key
    self.priv_key, unciphered = attack_module.attack(
  File "/home/lobsang/CTFtools/RsaCtfTool/attacks/single_key/z3_solver.py", line 49, in attack
    publickey.p = p.as_string()
AttributeError: 'NoneType' object has no attribute 'as_string'
Maybe its me using the program the wrong way, but I could not fix it. 
edit: I'm running this inside kali linux on wsl2

**Comment by Ganapati** [comment]
Fixed.
