### ISSUE TITLE
RsaCtfTool can only be called from it's own folder

### ISSUE THREAD

**Issue by noraj1337** [Ganapati/RsaCtfTool#2]
RsaCtfTool can only be called from it's own folder, from another PATH it can't find its ressources:

```
$ python2 ~/CTF/tools/RsaCtfTool/RsaCtfTool.py --publickey pub.key --private                                                                                                                                      
Traceback (most recent call last):
  File "/home/noraj/CTF/tools/RsaCtfTool/RsaCtfTool.py", line 370, in <module>
    attackobj.attack()
  File "/home/noraj/CTF/tools/RsaCtfTool/RsaCtfTool.py", line 261, in attack
    getattr(self, attack.__name__)()
  File "/home/noraj/CTF/tools/RsaCtfTool/RsaCtfTool.py", line 212, in pastctfprimes
    primes = [long(x) for x in open('pastctfprimes.txt','r').readlines() if not x.startswith('#') and not x.startswith('\n')]
IOError: [Errno 2] No such file or directory: 'pastctfprimes.txt'
```

**Comment by Ganapati** [comment]
Fixed with https://github.com/Ganapati/RsaCtfTool/commit/d6d1fd98eb199340b3de42b168dee9918759f8ae

Thx !
