### ISSUE TITLE
ValueError: no invmod for given @a and @n

### ISSUE THREAD

**Issue by subhamagr** [Ganapati/RsaCtfTool#228]
This was result of playing around with the tool. Following was the way I generated the value of `n`:

```
import os
from Crypto.Util import number

number.getPrime(2048, os.urandom)
```
I took the output of `number.getPrime(2048, os.urandom)` and replaced the last digit with an even number to generate a bad RSA key.

Command:
```
./RsaCtfTool.py --createpub -n 24114626302759667656781113938136847712920917259257002109976374427505611045469493205301407218253816426116794008667721812376620085594746706169887462073400438159888299496127985845126181600416883694121279585876475452829804311132468848998021639650871807016054723441488930871105024331637550340766724547081214892331141784785697014124774437542370285107171984841653185170962254093529117054975491679001908430102164339762687574995192322394345764525608278037390972692812761496501410486726493585577161784396720177851564743837562878669277505806586316167378988806416966386336834826900300509055031477719075261062895435261986332289374 -e 3
```

Public key:
```
-----BEGIN PUBLIC KEY-----
MIIBIDANBgkqhkiG9w0BAQEFAAOCAQ0AMIIBCAKCAQEAvwZOkcmqCkrSK/chFVM6
n53Q4K+tqmAIhixW8dxDmvJj1Ss3jOy+VSA3nou6wryVxR7UzV+ZXugR7eMaWLZF
DVO27NJK39kWQzOVI9T75XOiOgxRURb5qhKACAtNoJAqTNIWFCztVoNvT81m6EcM
TyGBF2Lk14waP6w4PvP4S0irs9zIJclB828fnrBTwZKYjxuhrpYZNFL3TXYMQAI1
qvw6j+N2LNNujK90TSDhs5wEO2qyWPJYfv3+yGIbVX0dGqErjBsCzedn6bNYttiF
LGnAeBiEqnNP2cG+wgTqrZxdHNnYgsEDU+Ds9IXVCEfPUiOni/JbIV4tbDOTbe0p
XgIBAw==
-----END PUBLIC KEY-----
```

command:
```
./RsaCtfTool.py --attack smallq --publickey ../app/pk.pem --private
```

Error Stack:
```
[*] Testing key ../app/pk.pem.
[*] Performing smallq attack on ../app/pk.pem.
Traceback (most recent call last):
  File "./RsaCtfTool.py", line 377, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/deploy/RsaCtfTool/lib/rsa_attack.py", line 242, in attack_single_key
    self.priv_key, unciphered = attack_module.attack(
  File "/deploy/RsaCtfTool/attacks/single_key/smallq.py", line 30, in attack
    priv_key = PrivateKey(
  File "/deploy/RsaCtfTool/lib/keys_wrapper.py", line 106, in __init__
    self.d = invmod(e, self.phi)
  File "/deploy/RsaCtfTool/lib/rsalibnum.py", line 23, in invmod
    raise ValueError("no invmod for given @a and @n")
ValueError: no invmod for given @a and @n
```

-----

Edit: Updating the value of `n` in the `createpub` command with last digit as `8` instead of `4` worked as expected.

**Comment by daedalus** [comment]
Hi, pr #229 is a partial solution i think.

**Comment by Ganapati** [comment]
Fixed with latest commit
