### ISSUE TITLE
Perfect square modulus crashes 

### ISSUE THREAD

**Issue by Antoxyde** [Ganapati/RsaCtfTool#239]
Basic example : 
```
>>> p = 257
>>> n = p*p
>>> e = 5
>>> c = pow(0x41,e,n)
7842
>>> n
66049
```
Here is the crash i obtain with up-to-date RsaCtfTool : 
```
$ python3.8 RsaCtfTool.py -n 66049 -e 5 --uncipher 7842
private argument is not set, the private key will not be displayed, even if recovered.

[*] Testing key /tmp/tmp34rw0js6.
Public key: /tmp/tmp34rw0js6 modulus is a perfect square
[*] Performing factordb attack on /tmp/tmp34rw0js6.
[*] Performing smallq attack on /tmp/tmp34rw0js6.
Traceback (most recent call last):
  File "RsaCtfTool.py", line 378, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/home/antox/repos/RsaCtfTool/lib/rsa_attack.py", line 285, in attack_single_key
    self.priv_key, unciphered = attack_module.attack(
  File "/home/antox/repos/RsaCtfTool/attacks/single_key/smallq.py", line 30, in attack
    priv_key = PrivateKey(
  File "/home/antox/repos/RsaCtfTool/lib/keys_wrapper.py", line 114, in __init__
    self.key = RSA.construct((self.n, self.e, self.d, self.p, self.q))
  File "/home/antox/.local/lib/python3.8/site-packages/Crypto/PublicKey/RSA.py", line 569, in construct
    u = p.inverse(q)
  File "/home/antox/.local/lib/python3.8/site-packages/Crypto/Math/_IntegerGMP.py", line 658, in inverse
    result.inplace_inverse(modulus)
  File "/home/antox/.local/lib/python3.8/site-packages/Crypto/Math/_IntegerGMP.py", line 653, in inplace_inverse
    raise ValueError("No inverse value can be computed")
ValueError: No inverse value can be computed
```
My guess is that phi is still computed as `(p-1)*-(q-1)` while for perfect square the formula is `(p-1) * p`, which leads to no inverse value found.

Also notice that it detected that the key was a perfect square (so factorisation is only square-root and we are done) but it still tried other method and ended up factoring with small q. This could be improved i think :-)

**Comment by daedalus** [comment]
Yes perfect squares are not suitable RSA keys since they are trivialy factored.
The pr#229 was intended catch this errors.
