### ISSUE TITLE
OverflowError: int too large to convert to float

### ISSUE THREAD

**Issue by JustYoomoon** [Ganapati/RsaCtfTool#271]
Hello, may I ask how to fix this error?

```
*] Performing pisano_period attack on ../pub.key.
Traceback (most recent call last):
  File "/home/kali/Desktop/RsaCtfTool-master/RsaCtfTool.py", line 396, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/home/kali/Desktop/RsaCtfTool-master/lib/rsa_attack.py", line 304, in attack_single_key
    self.priv_key, unciphered = attack_module.attack(
  File "/home/kali/Desktop/RsaCtfTool-master/attacks/single_key/pisano_period.py", line 123, in attack
    r = Fib.factorization(publickey.n,B1,B2)
  File "/home/kali/Desktop/RsaCtfTool-master/attacks/single_key/pisano_period.py", line 103, in factorization
    res = self.get_period_bigint(N, min_accept, xdiff) 
  File "/home/kali/Desktop/RsaCtfTool-master/attacks/single_key/pisano_period.py", line 50, in get_period_bigint
    search_len = int(pow(N, (1.0 / 6) / 100))
OverflowError: int too large to convert to float

```

**Comment by JustYoomoon** [comment]
![image](https://user-images.githubusercontent.com/80865985/123530680-d613f900-d72f-11eb-90dc-98523799e443.png)

**Comment by phalladar** [comment]
@JustYoomoon I was able to get around this problem temporarily by checking out a commit from a few months ago and re-running. I specifically used `git checkout 8bfd2a42096c1d24e1b840f8c74621768264bfcb`.

**Comment by Ganapati** [comment]
Can i have your inputs to test on my setup?

**Comment by Ganapati** [comment]
seems to be fixed in latest commit.
