### ISSUE TITLE
TypeError with RSA.construct

### ISSUE THREAD

**Issue by twelles** [Ganapati/RsaCtfTool#290]
When running the command: `python3 RsaCtfTool.py --publickey ../key.pub --uncipherfile ../flag.enc --private `, on a Kali box, I get the following output: 
```
[*] Testing key ../key.pub.
[*] Performing system_primes_gcd attack on ../key.pub.
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7007/7007 [00:00<00:00, 913994.34it/s]
[*] Performing mersenne_primes attack on ../key.pub.
 27%|█████████████████████████████████████████████████▍                                                                                                                                  | 14/51 [00:00<00:00, 441505.68it/s]
[*] Performing factordb attack on ../key.pub.
Traceback (most recent call last):
  File "/home/kali/OSCP/htb/RsaCtfTool/RsaCtfTool.py", line 433, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/home/kali/OSCP/htb/RsaCtfTool/lib/rsa_attack.py", line 304, in attack_single_key
    self.priv_key, unciphered = attack_module.attack(
  File "/home/kali/OSCP/htb/RsaCtfTool/attacks/single_key/factordb.py", line 85, in attack
    priv_key = PrivateKey(
  File "/home/kali/OSCP/htb/RsaCtfTool/lib/keys_wrapper.py", line 117, in __init__
    self.key = RSA.construct(
TypeError: construct() got an unexpected keyword argument 'consistency_check'
```

This is after running the Kali specific instructions.

**Comment by Ganapati** [comment]
fixed
