### ISSUE TITLE
Error in siqs.py

### ISSUE THREAD

**Issue by durranitech** [Ganapati/RsaCtfTool#31]
~/Documents/RsaCtfTool >>> ./RsaCtfTool.py --publickey ~/key.pub --private                                                                                                                             ±[●][master]
Traceback (most recent call last):
  File "./RsaCtfTool.py", line 658, in <module>
    attackobj.attack()
  File "./RsaCtfTool.py", line 478, in attack
    getattr(self, attack.__name__)()
  File "./RsaCtfTool.py", line 410, in siqs
    if siqsobj.checkyafu() and siqsobj.testyafu():
  File "/home/astro/Documents/RsaCtfTool/siqs.py", line 39, in testyafu
    if b'48670331' in yafutest:
TypeError: 'in <string>' requires string as left operand, not bytes

**Comment by durranitech** [comment]
Sorry. Is dupe. Closing this one
