### ISSUE TITLE
NotImplementedError: Use module Crypto.Cipher.PKCS1_OAEP instead

### ISSUE THREAD

**Issue by mrccn** [Ganapati/RsaCtfTool#40]
```
$ python3 RsaCtfTool.py --publickey pubkey.txt --uncipher 0123456789

Traceback (most recent call last):
  File "RsaCtfTool.py", line 95, in decrypt
    stderr=DN)
  File "/usr/lib64/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib64/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['openssl', 'rsautl', '-decrypt', '-in', '/tmp/tmpe5fwdqga', '-inkey', '/tmp/tmptc9stbjt']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "RsaCtfTool.py", line 724, in <module>
    attackobj.attack()
  File "RsaCtfTool.py", line 536, in attack
    self.unciphered = self.priv_key.decrypt(self.cipher)
  File "RsaCtfTool.py", line 98, in decrypt
    return self.key.decrypt(cipher)
  File "/usr/local/lib64/python3.6/site-packages/Crypto/PublicKey/RSA.py", line 378, in decrypt
    raise NotImplementedError("Use module Crypto.Cipher.PKCS1_OAEP instead")
NotImplementedError: Use module Crypto.Cipher.PKCS1_OAEP instead
```

I have `pycryptodome==3.6.6` installed but I get the same issue also with previews versions.

**Comment by Ganapati** [comment]
Fixed in latest commit. Thx for the issue !
