### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by bizibabe** [Ganapati/RsaCtfTool#97]
[*] Testing key pubkey.pem.
[*] Performing primefac attack on pubkey.pem.
Traceback (most recent call last):
  File "./RsaCtfTool.py", line 256, in <module>
    attackobj.attack_single_key(publickey, attacks_list)
  File "/root/Documents/RsaCtfTool/lib/rsa_attack.py", line 179, in attack_single_key
    self, self.publickey, self.cipher
  File "/root/Documents/RsaCtfTool/attacks/single_key/smallfraction.py", line 18, in attack
    ["sage", "./sage/smallfraction.sage", str(publickey.n)]
  File "/usr/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'sage': 'sage'

**Comment by Ganapati** [comment]
sage is not installed and my check for it is completely broken !
i'll fix this asap.
Try to run attacks by name and remove ecm,smallfraction, qicheng and boneh_durfee (they require sage)
